/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-12-26 09:51:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utils.JSFunction;

public final class mInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.JSFunction");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>홈페이지 소개</title>\r\n");
      out.write("<!-- style -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("   integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("   crossorigin=\"anonymous\">\r\n");
      out.write("<!-- script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/user.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("/*   .box{\r\n");
      out.write("      width:800px;\r\n");
      out.write("      height:700px;      \r\n");
      out.write("      margin:0 auto;\r\n");
      out.write("      opacity: 0.75;\r\n");
      out.write("      border-top-left-radius:20px;\r\n");
      out.write("      border-radius:5px;\r\n");
      out.write("      box-shadow: 5px 5px 5px 5px rgb(0,0,0,0.2);\r\n");
      out.write("      margin-top:10px;\r\n");
      out.write("      margin-bottom: 70px;\r\n");
      out.write("      position: relative;\r\n");
      out.write("   }*/\r\n");
      out.write(".text_1{\r\n");
      out.write("   padding-top:70px;\r\n");
      out.write("     color:#25a4cd;\r\n");
      out.write("     font-size: 20px;\r\n");
      out.write("     font-weight: bold;\r\n");
      out.write("     text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".text_1_1{\r\n");
      out.write("   padding-top:40px;\r\n");
      out.write("     color:#25a4cd;\r\n");
      out.write("     font-size: 20px;\r\n");
      out.write("     font-weight: bold;\r\n");
      out.write("     text-align: center;\r\n");
      out.write("     margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".t1 {\r\n");
      out.write("   margin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write(".text_2{\r\n");
      out.write("   color:#25a4cd;\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   margin-top: 60px;\r\n");
      out.write("   margin-bottom: 60px;\r\n");
      out.write("}\r\n");
      out.write(".p1{\r\n");
      out.write("   text-align:center;\r\n");
      out.write("   font-size:16px;\r\n");
      out.write("   padding-top:15px;\r\n");
      out.write("   color:gray;\r\n");
      out.write("   letter-spacing :1px;\r\n");
      out.write("   line-height: 2;\r\n");
      out.write("}\r\n");
      out.write(".namegroup{\r\n");
      out.write("   margin-left:170px;\r\n");
      out.write("}\r\n");
      out.write(".tname, .tmail{\r\n");
      out.write("   color:gray;\r\n");
      out.write("   font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write(".tmail{\r\n");
      out.write("   margin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write(".tname>.s1{\r\n");
      out.write("   margin-left: 200px;\r\n");
      out.write("}\r\n");
      out.write(".s2{\r\n");
      out.write("   margin-left:105px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tname>img, .s1>img{\r\n");
      out.write("   width:50px;\r\n");
      out.write("   height:80px;\r\n");
      out.write("   padding-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("         <div class=\"box\">   \r\n");
      out.write("               <p class=\"text_1\">홈페이지 소개</p>\r\n");
      out.write("               <p class=\"p1\">\r\n");
      out.write("               역사적으로 축적된 수 많은 우리의 자연, 인문자원들의 조화로운 풍경을 담아<br>\r\n");
      out.write("               AI 머신러닝을 통한 개개인의 취향에 맞춰, 체험하고 즐길 수 있도록 전국의 걷기 여행길을 소개해드립니다<br>\r\n");
      out.write("              \r\n");
      out.write("               <p class=\"text_1_1\">서비스 개요</p>\r\n");
      out.write("               <p class=\"p1 t1\">걷기 여행길의 활성화로 국민 건강증진 및 삶의 질 향상에 기여하는 것을 목표로<br> \r\n");
      out.write("               꼭 필요한 정보만 개인 맞춤으로 제공하는 편리성을 중점으로 한 서비스</p>\r\n");
      out.write("               <hr>\r\n");
      out.write("                <p class=\"text_2\">프로젝트 구성원</p>\r\n");
      out.write("                   <div class=\"namegroup\">\r\n");
      out.write("                        <p class=\"tname\"><img src=\"../resources/img/g.jpg\">한경훈 <span class=\"s1\"><img src=\"../resources/img/j.jpg\">김준영</span><span class=\"s1\"><img src=\"../resources/img/e.jpg\">김은주</span><span class=\"s1\"><img src=\"../resources/img/h.jpg\">박형준</span></p>\r\n");
      out.write("                        <p class=\"tmail\">de518n@naver.com &nbsp;&nbsp;&nbsp;&nbsp;<span class=\"s2\">fauleule@gmail.com</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=\"s2\">ej45423428@gmail.com</span><span class=\"s2\">kai11189@naver.com</span></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("              \r\n");
      out.write("         </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
