/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2023-01-03 07:07:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pref;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utils.JSFunction;

public final class pCategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.JSFunction");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>카테고리 선택</title>\r\n");
      out.write("<!-- style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/uCategory.css\">\r\n");
      out.write("<!-- script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/user.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("   body{\r\n");
      out.write("      background-image:url(\"../resources/bg/main_bg_img25.jpg\");\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header_main.jsp", out, false);
      out.write("\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      <div class=\"input-form-backgroud row\">\r\n");
      out.write("         <div class=\"input-form col-md-12 mx-auto\">\r\n");
      out.write("            <h4 class=\"join_title\">취향 선택</h4>\r\n");
      out.write("            <h4 class=\"join_text\">당신의 취향을 선택해 주세요</h4>\r\n");
      out.write("            \r\n");
      out.write("            <form action=\"/pOpt.pr\" method=\"post\" name=\"frm\">\r\n");
      out.write("               <div class=\"preference\">\r\n");
      out.write("                  <span class=\"thema_text\">| 장소</span>\r\n");
      out.write("                  <!-- <img src=\"../resources/img/area_w.png\" alt=\"x\" class=\"area_w\" data-toggle=\"tooltip\" title=\"장소\"> -->\r\n");
      out.write("                  <select class=\"pre_select\" name=\"category\">                     \r\n");
      out.write("                      <option value=\"0\">산</option>\r\n");
      out.write("                      <option value=\"1\">바다</option>\r\n");
      out.write("                      <option value=\"2\">강</option>\r\n");
      out.write("                      <option value=\"3\">도심</option>\r\n");
      out.write("                      <option value=\"4\">시골</option>\r\n");
      out.write("                      <option value=\"5\">섬</option>\r\n");
      out.write("                      <option value=\"6\">문화</option>\r\n");
      out.write("                      <option value=\"7\">역사</option>\r\n");
      out.write("                      <option value=\"8\">종교</option>\r\n");
      out.write("                      <option value=\"9\">관광</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"preference\">\r\n");
      out.write("                  <span class=\"thema_text\">| 테마</span>\r\n");
      out.write("                  <select class=\"pre_select\" name=\"keyword\">\r\n");
      out.write("                         <option value=\"자연\">자연</option>\r\n");
      out.write("                         <option value=\"체험\">체험</option>\r\n");
      out.write("                         <option value=\"전통\">전통</option>\r\n");
      out.write("                         <option value=\"종교\">종교</option>\r\n");
      out.write("                         <option value=\"도시\">도시</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"preference\">\r\n");
      out.write("                  <span class=\"thema_text\">| 지역</span>\r\n");
      out.write("                  <select class=\"pre_select\" name=\"area\">\r\n");
      out.write("                         <option value=\"서울\">서울</option>\r\n");
      out.write("                         <option value=\"경기\">경기</option>\r\n");
      out.write("                         <option value=\"인천\">인천</option>\r\n");
      out.write("                         <option value=\"세종\">세종</option>\r\n");
      out.write("                         <option value=\"대전\">대전</option>\r\n");
      out.write("                         <option value=\"충남\">충남</option>\r\n");
      out.write("                         <option value=\"충북\">충북</option>\r\n");
      out.write("                         <option value=\"광주\">광주</option>\r\n");
      out.write("                         <option value=\"전남\">전남</option>\r\n");
      out.write("                         <option value=\"전북\">전북</option>\r\n");
      out.write("                         <option value=\"대구\">대구</option>\r\n");
      out.write("                         <option value=\"경북\">경북</option>\r\n");
      out.write("                         <option value=\"부산\">부산</option>\r\n");
      out.write("                         <option value=\"울산\">울산</option>\r\n");
      out.write("                         <option value=\"경남\">경남</option>\r\n");
      out.write("                         <option value=\"강원\">강원</option>\r\n");
      out.write("                         <option value=\"제주\">제주</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"preference\">\r\n");
      out.write("                  <span class=\"thema_text1\">|난이도</span>\r\n");
      out.write("                  <select class=\"pre_select\" name=\"level\">\r\n");
      out.write("                         <option value=\"1\">매우쉬움</option>\r\n");
      out.write("                         <option value=\"2\">쉬움</option>\r\n");
      out.write("                         <option value=\"3\">보통</option>\r\n");
      out.write("                         <option value=\"4\">어려움</option>\r\n");
      out.write("                         <option value=\"5\">매우어려움</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"cagroup\">\r\n");
      out.write("               <button type=\"button\" class=\"Ca_button\" onclick=\"history.back(-1)\">&lt;&nbsp;&nbsp; 이전</button>\r\n");
      out.write("               <button type=\"submit\" class=\"Ca_button\">다음&nbsp;&nbsp; &gt;</button>\r\n");
      out.write("               </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer_main.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
