/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-12-26 09:27:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pref;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utils.JSFunction;

public final class pOption_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.JSFunction");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 취향 옵션</title>\r\n");
      out.write("<!-- style -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("   integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("   crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/uOption.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("   body {\r\n");
      out.write("		background-image: url(../resources/bg/main_bg_img22.jpg);\r\n");
      out.write("		background-size: cover;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("<!-- script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/user.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header_main.jsp", out, false);
      out.write("\r\n");
      out.write("   <div class=\"container\">   \r\n");
      out.write("      <div class=\"input_option\">\r\n");
      out.write("         <h4 class=\"join_title\">취향 선택</h4>\r\n");
      out.write("         <h4 class=\"join_text\">당신의 취향을 선택해 주세요</h4>\r\n");
      out.write("         <form action=\"/pResult.pr\" method=\"post\" id=\"frm\" name=\"frm\">\r\n");
      out.write("            <input type=\"hidden\" id=\"id\" name=\"id\" value=\"");
      out.print( session.getAttribute("id") );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"category\" name=\"category\" value=\"");
      out.print( request.getParameter("category") );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"keyword\" name=\"keyword\" value=\"");
      out.print( request.getParameter("keyword") );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"area\" name=\"area\" value=\"");
      out.print( request.getParameter("area") );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" id=\"level\" name=\"level\" value=\"");
      out.print( request.getParameter("level") );
      out.write("\">\r\n");
      out.write("            <div class=\"btn\">\r\n");
      out.write("               <h5 class=\"btn_title1\">편의시설</h5>\r\n");
      out.write("               <button class=\"btn_option\" type=\"button\" id=\"chkDrink\" name=\"chkDrink\" value=\"chkDrink\" onclick=\"chkOption(this)\">식수</button>\r\n");
      out.write("               <input type=\"hidden\" id=\"drink\" name=\"drink\" value=\"0\">\r\n");
      out.write("               <button class=\"btn_option\" type=\"button\" id=\"chkToilet\" name=\"chkToilet\" value=\"chkToilet\" onclick=\"chkOption(this)\">화장실</button>\r\n");
      out.write("               <input type=\"hidden\" id=\"toilet\" name=\"toilet\" value=\"0\">\r\n");
      out.write("               <button class=\"btn_option\" type=\"button\" id=\"chkMart\" name=\"chkMart\" value=\"chkMart\" onclick=\"chkOption(this)\">매점</button>\r\n");
      out.write("               <input type=\"hidden\" id=\"mart\" name=\"mart\" value=\"0\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"slidecontainer\">\r\n");
      out.write("               <h5 class=\"btn_title\">\r\n");
      out.write("                  길이 ( <span id=\"value\" name=\"length\"></span> km)\r\n");
      out.write("                  <input type=\"hidden\" id=\"length\" name=\"length\" value=\"50\">\r\n");
      out.write("               </h5>\r\n");
      out.write("               <input type=\"range\" min=\"0\" max=\"100\" step=\"1\" value=\"50\" class=\"form_range\" id=\"customRange1\">\r\n");
      out.write("               <label for=\"customRange3\" class=\"form-label\">0</label>\r\n");
      out.write("               <label for=\"customRange3\" class=\"form_label-2\">100 +</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <script type=\"text/javascript\">\r\n");
      out.write("               var slider = document.getElementById(\"customRange1\");\r\n");
      out.write("               var output = document.getElementById(\"value\");\r\n");
      out.write("               output.innerHTML = slider.value;\r\n");
      out.write("               \r\n");
      out.write("               slider.oninput = function() {\r\n");
      out.write("                  output.innerHTML = this.value;\r\n");
      out.write("                  document.getElementById(\"length\").value = this.value;\r\n");
      out.write("               }\r\n");
      out.write("            </script>\r\n");
      out.write("            <div class=\"slidecontainer\">\r\n");
      out.write("               <h5 class=\"btn_title\">\r\n");
      out.write("                  시간 ( <span id=\"value2\" name=\"time\"></span> 분)\r\n");
      out.write("                  <input type=\"hidden\" id=\"time\" name=\"time\" value=\"60\">\r\n");
      out.write("               </h5>\r\n");
      out.write("               <input type=\"range\" min=\"0\" max=\"360\" step=\"1\" value=\"60\"class=\"form_range\" id=\"customRange2\">\r\n");
      out.write("               <label for=\"customRange3\" class=\"form-label\">0</label>\r\n");
      out.write("               <label for=\"customRange3\" class=\"form_label-2\">360 +</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <script type=\"text/javascript\">\r\n");
      out.write("               var slider2 = document.getElementById(\"customRange2\");\r\n");
      out.write("               var output2 = document.getElementById(\"value2\");\r\n");
      out.write("               output2.innerHTML = slider2.value;\r\n");
      out.write("               \r\n");
      out.write("               slider2.oninput = function() {\r\n");
      out.write("                   output2.innerHTML = this.value;\r\n");
      out.write("                  document.getElementById(\"time\").value = this.value;\r\n");
      out.write("               }\r\n");
      out.write("            </script>\r\n");
      out.write("            <div class=\"cagroup\">\r\n");
      out.write("               <button type=\"button\" class=\"Ca_button\" onclick=\"history.back(-1);\">&lt;&nbsp;&nbsp; 이전</button>\r\n");
      out.write("               <button type=\"submit\" class=\"Ca_button\">완료&nbsp;&nbsp;&gt;</button>\r\n");
      out.write("            </div>\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer_main.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
