/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-12-23 07:50:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pref;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.UserDTO;
import model.SelectDTO;
import model.ReviewDTO;
import java.util.List;
import utils.JSFunction;

public final class pPref_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.JSFunction");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.UserDTO");
    _jspx_imports_classes.add("model.ReviewDTO");
    _jspx_imports_classes.add("model.SelectDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	if(session.getAttribute("id") == null){
		JSFunction.alertLocation(response, "잘못된 접근입니다.", "../main/mMain.jsp"); 
	}

	int pageNum = 0;
	int total_record = 0;
	int total_page = 0;
	List selectList = (List)request.getAttribute("list");
	UserDTO user = (UserDTO)request.getAttribute("udto");
	
	if(request.getAttribute("total_record") != null){
		total_record = ((Integer) request.getAttribute("total_record"));
	}
	if(request.getAttribute("pageNum") != null){
		pageNum = ((Integer) request.getAttribute("pageNum"));
	}
	if(request.getAttribute("total_page") != null){
		total_page = ((Integer) request.getAttribute("total_page"));
	}
	int start = 1;
	int end = 10;
	if(pageNum > 1){
		start = ((pageNum / 10) * 10) + 1;
		if(pageNum % 10 == 0){
			start = ((pageNum / 10) * 10) - 9;
		}
		end = start + 9;
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>취향길</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/pPref.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("	*{\r\n");
      out.write("	   margin:none;\r\n");
      out.write("	}\r\n");
      out.write("	button{background: inherit ; border:none;}\r\n");
      out.write("	\r\n");
      out.write("	.course_box>h3{\r\n");
      out.write("	   margin-top:70px;\r\n");
      out.write("	   margin-left:-390px;\r\n");
      out.write("	   margin-bottom: -30px;\r\n");
      out.write("	}\r\n");
      out.write("	.course_box>h3{\r\n");
      out.write("	   margin-top:70px;\r\n");
      out.write("	   margin-left:80px;\r\n");
      out.write("	   margin-bottom: -30px;\r\n");
      out.write("	}\r\n");
      out.write("	.btn_add{\r\n");
      out.write("	   height:40px;\r\n");
      out.write("	   margin-top:-180px;\r\n");
      out.write("	   margin-left:-400px;\r\n");
      out.write("	}\r\n");
      out.write("	.course_name{\r\n");
      out.write("	   font-size: 20px;\r\n");
      out.write("	   background-color:purple;\r\n");
      out.write("	   color:#fff;\r\n");
      out.write("	   border-radius:5px;\r\n");
      out.write("	   height: 45px;\r\n");
      out.write("	   width:110%;\r\n");
      out.write("	   margin-top: 80px;\r\n");
      out.write("	   padding-top:8px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.row{\r\n");
      out.write("	   border-bottom:1px solid purple;\r\n");
      out.write("	   width:127%;\r\n");
      out.write("	   height: 80px;\r\n");
      out.write("	   font-size: 16px;\r\n");
      out.write("	   float:left;\r\n");
      out.write("	   margin-left:10px;\r\n");
      out.write("	}\r\n");
      out.write("	.col{\r\n");
      out.write("	   display:flex;\r\n");
      out.write("	   align-items: center;\r\n");
      out.write("	   justify-content: center; \r\n");
      out.write("	}\r\n");
      out.write("	.col>img{\r\n");
      out.write("	   width:30px;\r\n");
      out.write("	   height:30px;   \r\n");
      out.write("	}\r\n");
      out.write("	.btngroup{\r\n");
      out.write("	   width: 150px;\r\n");
      out.write("	   margin-left:836px;\r\n");
      out.write("	   margin-top:-45px;\r\n");
      out.write("	   align-items: center;\r\n");
      out.write("	   display: flex;\r\n");
      out.write("	   flex-wrap: nowrap;\r\n");
      out.write("	}\r\n");
      out.write("	.btn_blue{\r\n");
      out.write("	   height: 45px;\r\n");
      out.write("	   button-border:1px solid purple;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.btn_blue:hover{\r\n");
      out.write("	   button-background-color: purple;\r\n");
      out.write("	   opacity: 0.75;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.modify{\r\n");
      out.write("	   margin-top: 150px;\r\n");
      out.write("	   margin-bottom: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	.form-control{\r\n");
      out.write("	   margin-top:20px;\r\n");
      out.write("	}\r\n");
      out.write("	.frist_text{\r\n");
      out.write("	   margin-top:40px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header.jsp", out, false);
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"contrainer\">   \r\n");
      out.write("         <div class=\"text-center course_box\">\r\n");
      out.write("            <h3>내 취향 리스트</h3>\r\n");
      out.write("            ");
	if(!selectList.isEmpty()){ 
      out.write("\r\n");
      out.write("	            ");

	            	for(int i = 0; i < selectList.size(); i++){
	            		SelectDTO select = (SelectDTO) selectList.get(i);
	            
      out.write("\r\n");
      out.write("	            <div class=\"course_name\">해오름길</div>            \r\n");
      out.write("	            <div class=\"row\">\r\n");
      out.write("	                <div class=\"col\"><img src=\"../resources/img/area_o.png\">");
      out.print( select.getArea() );
      out.write("</div>\r\n");
      out.write("	                <div class=\"col\"><img src=\"../resources/img/pref_o.png\">&nbsp;");
      out.print( select.getCategory() );
      out.write("</div>\r\n");
      out.write("	                <div class=\"col\"><img src=\"../resources/img/pref_o.png\">&nbsp;");
      out.print( select.getKeyword() );
      out.write("</div>\r\n");
      out.write("	                <div class=\"col\"><img src=\"../resources/img/level_o.png\">&nbsp;");
      out.print( select.getLevel() );
      out.write("</div>\r\n");
      out.write("	                <div class=\"col\"><img src=\"../resources/img/length_o.png\">&nbsp;");
      out.print( select.getLength() );
      out.write("</div>\r\n");
      out.write("	                <div class=\"col\"><img src=\"../resources/img/time_o.png\">&nbsp;");
      out.print( select.getTime() );
      out.write("</div>\r\n");
      out.write("	                <div class=\"col\"><img src=\"../resources/img/water_o.png\">&nbsp;");
      out.print( select.getWater() );
      out.write("</div>\r\n");
      out.write("	                <div class=\"col\"><img src=\"../resources/img/toilet_o.png\">&nbsp;");
      out.print( select.getToilet() );
      out.write("</div>\r\n");
      out.write("	                <div class=\"col\"><img src=\"../resources/img/mart_o.png\">&nbsp;");
      out.print( select.getMart() );
      out.write("</div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"btngroup\">\r\n");
      out.write("	               <button class=\"btn btn-outline-secondary btn_blue\" type=\"button\">수정</button>         \r\n");
      out.write("	               <button class=\"btn btn-outline-secondary btn_blue\" type=\"button\">삭제</button>   \r\n");
      out.write("	               <button class=\"btn btn-outline-primary btn_add\" type=\"button\">추가</button>   \r\n");
      out.write("	            </div>\r\n");
      out.write("	            <br><br>\r\n");
      out.write("            	");
	} 
      out.write("\r\n");
      out.write("            ");
	} else { 
      out.write("\r\n");
      out.write("            	<div class=\"row\">\r\n");
      out.write("	                <div class=\"col\"><p>취향 데이터가 존재하지 않습니다.</p></div>\r\n");
      out.write("	            </div>\r\n");
      out.write("           	");
	} 
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"input-form col-md-2 mx-auto modify\">\r\n");
      out.write("               <form action=\"#\" method=\"post\" id=\"frm\" name=\"frm\">\r\n");
      out.write("                  <h1 class=\"h3 mb-3 fw-normal\">개인정보 변경</h1>\r\n");
      out.write("                  <div class=\"mb-3\">\r\n");
      out.write("                     <input type=\"text\" class=\"form-control frist_text\" id=\"upw\" placeholder=\"비밀번호\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"mb-3\">\r\n");
      out.write("                     <input type=\"password\" class=\"form-control\" id=\"chkpw\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"mb-3\">\r\n");
      out.write("                      <input type=\"text\" id=\"tel\" name=\"tel\" class=\"form-control\" placeholder=\" - 없이 전화번호\" maxlength=\"11\" onKeyup=\"this.value=this.value.replace(/[^0-9]/g,'');\" value=\"");
      out.print( user.getUtel() );
      out.write("\">\r\n");
      out.write("                     <div class=\"invalid-feedback\">전화번호를 입력해주세요.</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <button class=\"w-10 btn btn-primary\" type=\"button\">정보 변경</button>\r\n");
      out.write("               </form>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("   \r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
