/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2023-01-10 03:56:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import utils.JSFunction;

public final class uJoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.JSFunction");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   if(session.getAttribute("id") != null){
      JSFunction.alertLocation(response, "잘못된 접근입니다.", "../main/mMain.jsp"); 
   }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>회원가입 화면</title>\r\n");
      out.write("<!-- style -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("   integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("   crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/uJoin.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("   body{\r\n");
      out.write("      background-image: url(../resources/bg/main_bg_img20.jpg);\r\n");
      out.write("   }\r\n");
      out.write("   tr:nth-child(2n){\r\n");
      out.write("	height: 20px;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("<!-- script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/user.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	// ID 중복검사\r\n");
      out.write("	function confirmId(){\r\n");
      out.write("		let idReg = /^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d~!@#$%^&*()+|=]{6,12}$/;	// 영문자, 숫자 1개이상 필수, 6~12글자\r\n");
      out.write("		if(joinFrm.id.value == null || joinFrm.id.value == \"\"){	// id 입력란 공백 체크\r\n");
      out.write("			alert(\"ID를 입력해주세요.\");\r\n");
      out.write("			joinFrm.id.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		} else if (!idReg.test(joinFrm.id.value)) {	// 유효성 검사\r\n");
      out.write("			alert(\"아이디는 영문자+숫자로 6자리 이상을 사용하세요.\");\r\n");
      out.write("			joinFrm.id.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		} \r\n");
      out.write("		let popWidth = 300;		/* 팝업 가로길이 */\r\n");
      out.write("		let popHeight = 200;	/* 팝업 세로길이 */\r\n");
      out.write("		let popX = (window.screen.width / 2) - (popWidth / 2);		/* 팝업 가로위치 지정 */\r\n");
      out.write("		let popY = (window.screen.height / 2) - (popHeight / 2);	/* 팝업 세로위치 지정 */\r\n");
      out.write("		url = \"./user/uChkId.jsp?id=\" + joinFrm.id.value;	/* 중복결과화면 주소 */\r\n");
      out.write("		open(url, \"confirm\", \"toolbar=no, location=no, status=no, menubar=no, resizable=no, width=\"+popWidth+\", height=\"+popHeight+\", left=\"+popX+\" ,top=\"+popY);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/header_main.jsp", out, false);
      out.write("\r\n");
      out.write("   <div class=\"container hei\">\r\n");
      out.write("      <div class=\"my-auto d-flex justify-content-center text-center\">\r\n");
      out.write("         <form action=\"/uCate.us\" method=\"post\" id=\"joinFrm\" name=\"joinFrm\">\r\n");
      out.write("            <h5 class=\"join_text mb-3\">회원 가입</h5>\r\n");
      out.write("            <table>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	            	<td>\r\n");
      out.write("		            	<label>ID</label>\r\n");
      out.write("	            	</td>\r\n");
      out.write("	            	<td>\r\n");
      out.write("		            	<input type=\"text\" id=\"id\" name=\"id\" class=\"join_tag join_id\" placeholder=\"ID : 영문+숫자 포함 6~12\" maxlength=\"12\">\r\n");
      out.write("		            	<button class=\"chkId\" type=\"button\" id=\"chkId\" name=\"chkId\" onclick=\"confirmId(this.form)\">ID 중복검사</button>\r\n");
      out.write("	            	</td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	            	<td>\r\n");
      out.write("		            	<label>비밀번호</label>\r\n");
      out.write("	            	</td>\r\n");
      out.write("	            	<td>\r\n");
      out.write("		               <input type=\"password\" id=\"pw\" name=\"pw\" class=\"join_tag\" placeholder=\"비밀번호 : 영문+숫자+특수문자 포함 8~20\" maxlength=\"25\">\r\n");
      out.write("	            	</td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	            	<td>\r\n");
      out.write("		            	<label>이름</label>\r\n");
      out.write("	            	</td>\r\n");
      out.write("	            	<td>\r\n");
      out.write("		               <input type=\"text\" id=\"name\" name=\"name\" class=\"join_tag\" placeholder=\"이름\" maxlength=\"5\">\r\n");
      out.write("	            	</td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	            	<td>\r\n");
      out.write("		            	<label>전화번호</label>\r\n");
      out.write("	            	</td>\r\n");
      out.write("	            	<td>\r\n");
      out.write("		               <input type=\"text\" id=\"tel\" name=\"tel\" class=\"join_tag\" placeholder=\" - 없이 전화번호\" maxlength=\"11\" onKeyup=\"this.value=this.value.replace(/[^0-9]/g,'');\">\r\n");
      out.write("	            	</td>\r\n");
      out.write("	            </tr>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	            </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <div class=\"ca-group\">\r\n");
      out.write("				<button type=\"button\" class=\"Ca_button\" onclick=\"location.href='../main/mMain.jsp'\">&lt;&nbsp;&nbsp; 홈</button>\r\n");
      out.write("				<button type=\"button\" class=\"Ca_button\" onclick=\"chkForm()\">다음&nbsp;&nbsp; &gt;</button>\r\n");
      out.write("            </div>\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"footer\">\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer_main.jsp", out, false);
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
